fixed Emacs typo

diff --git a/install/setup-emacs b/install/setup-emacs
--- a/install/setup-emacs
+++ b/install/setup-emacs
@@ -1,25 +1,25 @@
 #!/bin/bash
 set -e
 
-SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
 source "$SCRIPT_DIR/lib/helpers.sh"
 source "$SCRIPT_DIR/lib/backup.sh"
 DOTFILES_DIR="$HOME/.local/share/dotfiles"
 
 if [ -d "$HOME/.config/emacs" ] || [ -L "$HOME/.config/emacs" ]; then
-  log_info "Existing nvim config found, backing up..."
-  if [ -e "$HOME/.config/emacs" ]; then
-    backup_file "$HOME/.config/emacs" || {
-      log_error "Failed to backup emacs config"
-      exit 1
-    }
-  fi
-  remove_path "$HOME/.config/emacs"
+	log_info "Existing nvim config found, backing up..."
+	if [ -e "$HOME/.config/emacs" ]; then
+		backup_file "$HOME/.config/emacs" || {
+			log_error "Failed to backup emacs config"
+			exit 1
+		}
+	fi
+	remove_path "$HOME/.config/emacs"
 fi
 
-if ! git clone git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs; then
-  log_error "Failed to clone Doom Emacs"
-  exit 1
+if ! git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs; then
+	log_error "Failed to clone Doom Emacs"
+	exit 1
 fi
 #rm -rf ~/.config/nvim/.git
 log_info "Doom Emacs cloned"
